const CATEGORY_NAME_MIN_LENGTH = 2;
const CATEGORY_NAME_MAX_LENGTH = 50;

const CATEGORY_DESCRIPTION_MIN_LENGTH = 2;
const CATEGORY_DESCRIPTION_MAX_LENGTH = 1500;

module.exports = {
  CATEGORY_NAME_MIN_LENGTH,
  CATEGORY_NAME_MAX_LENGTH,
  CATEGORY_DESCRIPTION_MIN_LENGTH,
  CATEGORY_DESCRIPTION_MAX_LENGTH,
};
