export {
  APP_PORT,
  CORS_ORIGIN,
  MONGO_URI,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET_EXPIRY,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET_EXPIRY,
  MAIL_TRAP_HOST,
  MAIL_TRAP_PORT,
  MAIL_TRAP_USER_NAME,
  MAIL_TRAP_USER_PASS,
  FRONTEND_HOST,
} from './secrets';
