const PRODUCT_NAME_MIN_LENGTH = 2;
const PRODUCT_NAME_MAX_LENGTH = 50;

const PRODUCT_DESCRIPTION_MIN_LENGTH = 2;
const PRODUCT_DESCRIPTION_MAX_LENGTH = 1500;

module.exports = {
  PRODUCT_NAME_MIN_LENGTH,
  PRODUCT_NAME_MAX_LENGTH,
  PRODUCT_DESCRIPTION_MIN_LENGTH,
  PRODUCT_DESCRIPTION_MAX_LENGTH,
};
